### ISSUE TITLE
Remove advanced CSS properties?

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/html-css-layout#10]
@jrhorn424 & I believe media queries are out of scope for this lesson, @gaand do you agree?

**Comment by jrhorn424** [comment]
Which sections did we discuss de-scoping? I believe it was media queries.

**Comment by gaand** [comment]
I remember discussing media queries.  I believe we concluded that such things should be left to bootstrap and or be in additional resources.

**Comment by jrhorn424** [comment]
@ga-wdi-boston/core Where are we on this? I've had conversations recently, and I can't remember with who, that these should remain.

I believe they're best left to bootstrap. IMO, media queries are something that can be learned on-the-job. That said, if there is disagreement, let's record it here.

**Comment by gaand** [comment]
I do not have a strong opinion at this time.

@laurenfazah Would you care to comment?

**Comment by laurenfazah** [comment]
@gaand @jrhorn424 I understand the benefit of leaving that to bootstrap. I, personally, am pro keeping media queries in the lesson for front-end pedagogy. [In my opinion,] Front end developers for hire won't be attractive without media query knowledge. Relying on bootstrap for aesthetic purposes is fine. But relying on it for core CSS concepts is another thing. I believe this is the only core CSS concept we would push solely onto Bootstrap, yes? I'd rather descope this lesson by removing the position segment (seeing as developers usually don't pay attention to that until they run into a specific need for it).

**Comment by gaand** [comment]
Based on Lauren's response, I would have to have clear trade offs expressed before agreeing that media queries should not be covered briefly.

**Comment by raq929** [comment]
I agree with Lauren, and am going to leave them in for wdi-015. 
@berziiii Is it OK to close this issue?

**Comment by gaand** [comment]
@berziiii @jrhorn424 I'm going to close.  If I'm wrong, please reopen.  Thanks.
