### ISSUE TITLE
Tell students to complete the labs in CodePen.io

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/html-css-layout#8]

**Comment by jrhorn424** [comment]
If we had front-end tooling ready next time, would you still find it useful to have students use CodePen?

I guess I just wonder what motivated this issue. Thanks!

**Comment by GA-MEB** [comment]
Easily spinning up something new, just to play around with stuff. But yeah, given today's conversation, I think tooling is the way we want to go. Closing this issue and making a new one for tooling.
