### ISSUE TITLE
Structure lesson to use WebPack tooling.

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/html-css-layout#9]
See https://github.com/ga-wdi-boston/planning/issues/5
(Formerly https://github.com/ga-wdi-boston/010/issues/4)

**Comment by berziiii** [comment]
@gaand it appears that the lesson has WebPack tooling incorporate. If so, can we close this issue? Thanks.

**Comment by gaand** [comment]
Cloned, npm installed, grunt served,  All looked good
